import type { ServiceType, GalleryStatus, PreventivoStato, PreventivoTemplate } from './types'

export const SERVICE_TYPES: ServiceType[] = [
  'Matrimonio',
  'Promessa di Matrimonio',
  'Battesimo',
  'Comunione',
  '1 Anno',
  '18 Anni',
  'Anniversario',
  'Shooting Fotografico',
  'Altra Cerimonia',
  'Ritratto',
  'Famiglia',
  'Moda / Editorial',
  'Corporate',
  'Evento',
  'Newborn',
]

export const SERVICE_TYPES_CERIMONIE: ServiceType[] = [
  'Matrimonio',
  'Promessa di Matrimonio',
  'Battesimo',
  'Comunione',
  '1 Anno',
  '18 Anni',
  'Anniversario',
  'Shooting Fotografico',
  'Altra Cerimonia',
]

export const PREVENTIVO_TEMPLATES: PreventivoTemplate[] = [
  {
    id: 'matrimonio-silver',
    nome: 'Matrimonio Silver',
    servizio: 'Matrimonio',
    descrizione: 'Pacchetto completo per matrimoni fino a 6 ore di copertura',
    durata_ore: 6,
    colore: '#8ec9b0',
    voci: [
      { desc: 'Servizio fotografico cerimonia (6 ore)', prezzo: 1200 },
      { desc: 'Galleria online privata con 400 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 150 },
      { desc: 'Stampe 20×30 cm (10 pz)', prezzo: 150 },
    ],
    totale: 1500,
  },
  {
    id: 'matrimonio-gold',
    nome: 'Matrimonio Gold',
    servizio: 'Matrimonio',
    descrizione: 'Pacchetto premium con album fotografico e copertura giornata intera',
    durata_ore: 10,
    colore: '#c9a05a',
    voci: [
      { desc: 'Servizio fotografico giornata completa (10 ore)', prezzo: 1800 },
      { desc: 'Album fotografico 30×30 cm (100 pagine)', prezzo: 800 },
      { desc: 'Galleria online privata con 600 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 150 },
      { desc: 'Stampe fine art 20×30 cm (20 pz)', prezzo: 250 },
    ],
    totale: 3000,
  },
  {
    id: 'matrimonio-platinum',
    nome: 'Matrimonio Platinum',
    servizio: 'Matrimonio',
    descrizione: 'Il massimo: due fotografi, album doppio e servizio pre-matrimoniale',
    durata_ore: 12,
    colore: '#b0b8c9',
    voci: [
      { desc: 'Due fotografi per 12 ore', prezzo: 3200 },
      { desc: 'Shooting pre-matrimoniale (2 ore)', prezzo: 400 },
      { desc: 'Album fotografico 30×40 cm (120 pagine)', prezzo: 1200 },
      { desc: 'Album sposi piccolo 20×20 cm', prezzo: 350 },
      { desc: 'Galleria online privata illimitata', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 150 },
      { desc: 'Stampe fine art 30×40 cm (20 pz)', prezzo: 400 },
    ],
    totale: 5700,
  },
  {
    id: 'battesimo-base',
    nome: 'Battesimo',
    servizio: 'Battesimo',
    descrizione: 'Cerimonia e festeggiamenti con galleria online',
    durata_ore: 4,
    colore: '#9bc4e2',
    voci: [
      { desc: 'Servizio fotografico cerimonia + festeggiamenti (4 ore)', prezzo: 500 },
      { desc: 'Galleria online privata con 200 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
      { desc: 'Stampe 15×20 cm (5 pz)', prezzo: 60 },
    ],
    totale: 660,
  },
  {
    id: 'battesimo-premium',
    nome: 'Battesimo + Album',
    servizio: 'Battesimo',
    descrizione: 'Con album fotografico 20×20 cm da 40 pagine',
    durata_ore: 5,
    colore: '#9bc4e2',
    voci: [
      { desc: 'Servizio fotografico cerimonia + festeggiamenti (5 ore)', prezzo: 600 },
      { desc: 'Album fotografico 20×20 cm (40 pagine)', prezzo: 350 },
      { desc: 'Galleria online privata con 250 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
    ],
    totale: 1050,
  },
  {
    id: 'comunione-base',
    nome: 'Prima Comunione',
    servizio: 'Comunione',
    descrizione: 'Cerimonia, preparativi e festeggiamenti',
    durata_ore: 5,
    colore: '#e8c9a0',
    voci: [
      { desc: 'Servizio fotografico cerimonia + preparativi (5 ore)', prezzo: 600 },
      { desc: 'Galleria online privata con 250 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
      { desc: 'Stampe 15×20 cm (10 pz)', prezzo: 100 },
    ],
    totale: 800,
  },
  {
    id: 'comunione-album',
    nome: 'Prima Comunione + Album',
    servizio: 'Comunione',
    descrizione: 'Con album fotografico e stampe di pregio',
    durata_ore: 6,
    colore: '#e8c9a0',
    voci: [
      { desc: 'Servizio fotografico cerimonia + festeggiamenti (6 ore)', prezzo: 750 },
      { desc: 'Album fotografico 20×20 cm (50 pagine)', prezzo: 400 },
      { desc: 'Galleria online privata con 300 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
      { desc: 'Stampe fine art 20×30 cm (10 pz)', prezzo: 150 },
    ],
    totale: 1400,
  },
  {
    id: 'primo-anno',
    nome: '1° Compleanno',
    servizio: '1 Anno',
    descrizione: 'Shooting del primo compleanno con palloncini e torta',
    durata_ore: 2,
    colore: '#c9a0e8',
    voci: [
      { desc: 'Shooting primo compleanno in studio (2 ore)', prezzo: 250 },
      { desc: 'Galleria online privata con 80 foto selezionate', prezzo: 0 },
      { desc: '25 file HD scaricabili', prezzo: 0 },
      { desc: 'Stampe 15×20 cm (5 pz)', prezzo: 60 },
    ],
    totale: 310,
  },
  {
    id: 'primo-anno-premium',
    nome: '1° Compleanno Premium',
    servizio: '1 Anno',
    descrizione: 'In studio + esterna, con album ricordo',
    durata_ore: 3,
    colore: '#c9a0e8',
    voci: [
      { desc: 'Shooting primo compleanno in studio + esterna (3 ore)', prezzo: 380 },
      { desc: 'Mini album 15×15 cm (20 pagine)', prezzo: 180 },
      { desc: 'Galleria online privata con 120 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 80 },
    ],
    totale: 640,
  },
  {
    id: 'diciotto-anni',
    nome: '18° Compleanno',
    servizio: '18 Anni',
    descrizione: 'Festa e preparativi, galleria con le migliori foto',
    durata_ore: 5,
    colore: '#e8a0b4',
    voci: [
      { desc: 'Servizio fotografico festa (5 ore)', prezzo: 600 },
      { desc: 'Galleria online privata con 300 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
      { desc: 'Stampe 20×30 cm (10 pz)', prezzo: 150 },
    ],
    totale: 850,
  },
  {
    id: 'diciotto-anni-shooting',
    nome: '18° Compleanno + Shooting',
    servizio: '18 Anni',
    descrizione: 'Shooting personale pre-festa + copertura evento',
    durata_ore: 7,
    colore: '#e8a0b4',
    voci: [
      { desc: 'Shooting personale pre-festa (2 ore)', prezzo: 300 },
      { desc: 'Servizio fotografico festa (5 ore)', prezzo: 550 },
      { desc: 'Album fotografico 20×20 cm (40 pagine)', prezzo: 350 },
      { desc: 'Galleria online privata con 350 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
    ],
    totale: 1300,
  },
  {
    id: 'anniversario-base',
    nome: 'Anniversario',
    servizio: 'Anniversario',
    descrizione: 'Rinnovo dei momenti speciali con shooting di coppia',
    durata_ore: 2,
    colore: '#a0c4e8',
    voci: [
      { desc: 'Shooting di coppia (2 ore)', prezzo: 300 },
      { desc: 'Galleria online privata con 100 foto', prezzo: 0 },
      { desc: '30 file HD scaricabili', prezzo: 0 },
      { desc: 'Stampe fine art 20×30 cm (5 pz)', prezzo: 100 },
    ],
    totale: 400,
  },
  {
    id: 'anniversario-premium',
    nome: 'Anniversario Premium',
    servizio: 'Anniversario',
    descrizione: 'Shooting di coppia + cerimonia simbolica + album',
    durata_ore: 4,
    colore: '#a0c4e8',
    voci: [
      { desc: 'Shooting di coppia in location (4 ore)', prezzo: 550 },
      { desc: 'Album fotografico 20×20 cm (30 pagine)', prezzo: 300 },
      { desc: 'Galleria online privata con 200 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
      { desc: 'Stampe fine art 30×40 cm (3 pz)', prezzo: 150 },
    ],
    totale: 1100,
  },
  {
    id: 'shooting-base',
    nome: 'Shooting Fotografico',
    servizio: 'Shooting Fotografico',
    descrizione: 'Ritratto o shooting personale in studio o esterna',
    durata_ore: 2,
    colore: '#8ec9b0',
    voci: [
      { desc: 'Sessione fotografica (2 ore)', prezzo: 200 },
      { desc: 'Galleria online con 60 foto selezionate', prezzo: 0 },
      { desc: '20 file HD scaricabili', prezzo: 0 },
    ],
    totale: 200,
  },
  {
    id: 'shooting-premium',
    nome: 'Shooting Fotografico Premium',
    servizio: 'Shooting Fotografico',
    descrizione: 'Con cambio outfit, location multipla e più foto',
    durata_ore: 3,
    colore: '#8ec9b0',
    voci: [
      { desc: 'Sessione fotografica con 2 outfit (3 ore)', prezzo: 350 },
      { desc: 'Galleria online con 100 foto selezionate', prezzo: 0 },
      { desc: '40 file HD scaricabili', prezzo: 0 },
      { desc: 'Ritocco avanzato su 5 foto scelte', prezzo: 100 },
    ],
    totale: 450,
  },
  {
    id: 'altra-cerimonia',
    nome: 'Altra Cerimonia',
    servizio: 'Altra Cerimonia',
    descrizione: 'Cresima, laurea, evento speciale o ricorrenza',
    durata_ore: 4,
    colore: '#b0a0e8',
    voci: [
      { desc: 'Servizio fotografico cerimonia (4 ore)', prezzo: 500 },
      { desc: 'Galleria online privata con 200 foto', prezzo: 0 },
      { desc: 'USB con tutte le foto in HD', prezzo: 100 },
      { desc: 'Stampe 15×20 cm (5 pz)', prezzo: 60 },
    ],
    totale: 660,
  },
]

export const GALLERY_STATUSES: { value: GalleryStatus; label: string }[] = [
  { value: 'active',   label: 'Attiva' },
  { value: 'draft',    label: 'Bozza' },
  { value: 'archived', label: 'Archiviata' },
]

export const PREVENTIVO_STATI: { value: PreventivoStato; label: string }[] = [
  { value: 'bozza',     label: 'Bozza' },
  { value: 'inviato',   label: 'Inviato' },
  { value: 'accettato', label: 'Accettato' },
  { value: 'rifiutato', label: 'Rifiutato' },
]

export const DEFAULT_GALLERY_SETTINGS = {
  preferiti: true,
  commenti: true,
  social: false,
  servizio_stampa: false,
  download_singolo: true,
  download_hd: false,
  download_zip: false,
  watermark: false,
  nome_file: false,
  pagamenti: {
    negozio: false,
    paypal: false,
    bonifico: false,
  },
}

export const DEFAULT_COVER_COLOR = '#2a3830'
